### ISSUE TITLE
Runtime requires don't work with browserify / commonjs packagers.

### ISSUE THREAD

**Issue by Industrial** [chaplinjs/chaplin#742]
Since it statically analizes the source code.

https://github.com/chaplinjs/chaplin/blob/master/src/chaplin/dispatcher.coffee#L101

this causes a require but its ran by chaplin on the client and not by browserify on the server, so by that time browserify already made the bundled file and it doesn't include any controllers.

A solution would be a way to decouple loading from instantiating of controllers in the Dispatcher..

**Comment by rachel-carvalho** [comment]
For posterity: I've updated @chrisabrams's basic Chaplin + browserify sample app, but I'm using gulp instead of Grunt and Javascript instead of CoffeeScript (though this one is not by choice :P):
https://github.com/rachel-carvalho/chaplin-browserify-gulp
