### ISSUE TITLE
Subview's noWrap property doesn't work

### ISSUE THREAD

**Issue by vadikace** [chaplinjs/chaplin#821]
``` coffeescript
# Somewhere in main view
@subview "subview", new SomeSubview { model: element, container: '#somecontainer' }

# While initing SomeSubview
class SomeSubview extends View
  autoRender: true
  noWrap: true
  template: template
```

Despite noWrap property in SomeSubview chaplin still wraps template in div.

**Comment by narensgh** [comment]
@akre54, could you please explain how can I apply a class on the same div which I assigned as listSelector on collectionView? Because it adds 2 different divs one as listSelector with id and one as inner div with class name.
Thanks
