### ISSUE TITLE
Is it possible to hide and show View without to dispose them?

### ISSUE THREAD

**Issue by danielefenix** [chaplinjs/chaplin#835]
Good morning everyone,

First of all I want to thank you for the project. I recently discover it and it seems to address all the issue I faced during the implementation of a recent project i took part of. I am excited to try it.

Going through the documentation I understood the the power of memory management of the library lies on a the process of disposing of the views (following its controller disposition). 

In my case, a mobile app project, it is not convenient to remove completely a view because its content is generated after heavy computation and at the moment I instantiate the views on their fist show, and hide/show after it. 
I noticed the hideOldView() and showNewView() methods but I am not sure they are what i need.

I would like to know if ChaplinJS gives the possibility to achieve it. If yes, could you provide an example?

Thank you very much in advice for your reply and your time.

**Comment by ogonkov** [comment]
Should be closed?
