### ISSUE TITLE
View::render - return origin result from wrapped method

### ISSUE THREAD

**Issue by jeron-diovis** [chaplinjs/chaplin#849]
https://github.com/chaplinjs/chaplin/blob/master/src%2Fchaplin%2Fviews%2Fview.coffee#L141
Why need to force returning a view instance? 
If you wrap origin method, which can be extended or even totally overridden, isn't it reasonable to care about returning it's origin result?

**Comment by paulmillr** [comment]
force? no one is forcing it. you can return anything you want. the result is not usually used anywhere

**Comment by jeron-diovis** [comment]
I don't understand you. Whatever I return from `render` in my view class definition, when view is instantiated, that `render` is wrapped to function, which always returns `this`. Just what is shown by link above, actually.
In **runtime** I can't "return anything I want".
Yes, result of `render` is not usually used anywhere in runtime, but if it is - we have a problem here.

**Comment by molily** [comment]
You mean it should be:
```
@render = =>
  # …
  returnValue = render.apply this, arguments
  # …
  returnValue
```
?

**Comment by jeron-diovis** [comment]
Yes, exactly.

**Comment by molily** [comment]
Agreed!
