### ISSUE TITLE
Backbone 1.2.0

### ISSUE THREAD

**Issue by akre54** [chaplinjs/chaplin#860]
Backbone is now 1.2.0. Anyone want to try and get #780 in?

**Comment by Florian-R** [comment]
@akre54 Totally forgot my pending PR on your fork (sorry for this). I'll try to check this soon if i can. IIRC, there's not much work to be done.

**Comment by akre54** [comment]
Cool, thanks!

**Comment by alekbarszczewski** [comment]
:+1:
