### ISSUE TITLE
(npm) Update to newer Backbone

### ISSUE THREAD

**Issue by mindrones** [chaplinjs/chaplin#869]
I'm trying Chaplin with Browserify and it seems that it depends on Backbone 1.1.2. 
I'd need Backbone to require jquery automatically but it does it in version 1.2.x (see [this commit](https://github.com/jashkenas/backbone/commit/b2a10afe4b85c15f0dc4955e3bfaa9a4590cc851)).

Can you update Backbone to 1.2.3?
Thanks!

**Comment by akre54** [comment]
The bulk of the work that needs to be done is in #780. It still has some failing tests, if you can help with those we can upgrade right away.

**Comment by paulmillr** [comment]
done

**Comment by mindrones** [comment]
@paulmillr thanks! Can you share when this will be available in npm?

**Comment by paulmillr** [comment]
need to merge a few more adjustments for 1.2
