### ISSUE TITLE
Uncaught TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by ktktok** [chaplinjs/chaplin#882]
Sometimes I am getting this error in my application and in ost.io when move from CollectionView. [http://i.stack.imgur.com/bou7z.png](http://i.stack.imgur.com/bou7z.png)

**Comment by paulmillr** [comment]
@goshakkk

**Comment by goshakkk** [comment]
@ktktok is there a particular page in ost.io that it consistently happens on, or any other navigation flow to that consistently reproduces the issue?

**Comment by ktktok** [comment]
I found STR:
Open http://ost.io/@brunch
Click on "brunch" for example
Click on browser "back" and "forward" buttons

**Comment by goshakkk** [comment]
Hm. Couldn't get that to produce anything in both Safari and Chrome

**Comment by ktktok** [comment]
http://screencast.com/t/fdaBhLR6Z

**Comment by goshakkk** [comment]
@ktktok I see, the key here seems to be clicking back/forward fast enough before any content on these pages is loaded. Thanks, I was able to reproduce that and will be looking into it

**Comment by ktktok** [comment]
Thanks!

**Comment by goshakkk** [comment]
That was happening because `this._byId` on collection view was deleted during `dispose`, but some calls to `get` happened even after that. It's safer to reset `_byId` to an empty object so that it doesn't raise an error. #890 should fix that.
